# Generated by Django 2.2 on 2019-05-26 15:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedlyAPISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FEEDLY_API_CLIENT_ID', models.CharField(blank=True, help_text='Use “feedlydev” for the client_id if you have developer access token', max_length=200)),
                ('FEEDLY_API_CLIENT_SECRET', models.CharField(blank=True, help_text='Use “feedlydev” for the client_secret if you have developer access token', max_length=200)),
                ('FEEDLY_API_REFRESH_TOKEN', models.CharField(blank=True, max_length=200)),
                ('FEEDLY_API_ACCESS_TOKEN', models.CharField(blank=True, help_text='Automatically refreshes if you have feedly pro or team account', max_length=200)),
            ],
            options={
                'verbose_name': 'Feedly Configuration',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='posts.Comment'),
        ),
    ]
