# Generated by Django 2.2 on 2019-05-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190526_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlyapisettings',
            name='api_requests_remained',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_CLIENT_ID',
            field=models.CharField(blank=True, default='feedlydev', help_text='Use “feedlydev” for the client_id if you have developer access token', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_CLIENT_SECRET',
            field=models.CharField(blank=True, default='feedlydev', help_text='Use “feedlydev” for the client_secret if you have developer access token', max_length=200),
        ),
    ]
