# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-04-14 16:45
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190314_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news_site_logo',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=b'news_site_logos/'),
        ),
    ]
