# Generated by Django 2.2 on 2019-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190512_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hubspot_contact',
            field=models.BooleanField(default=False),
        ),
    ]
