# Generated by Django 2.2 on 2019-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190526_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_ACCESS_TOKEN',
            field=models.CharField(blank=True, help_text='Automatically refreshes if you have feedly pro or team account', max_length=400),
        ),
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_CLIENT_ID',
            field=models.CharField(blank=True, default='feedlydev', help_text='Use “feedlydev” for the client_id if you have developer access token', max_length=400),
        ),
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_CLIENT_SECRET',
            field=models.CharField(blank=True, default='feedlydev', help_text='Use “feedlydev” for the client_secret if you have developer access token', max_length=400),
        ),
        migrations.AlterField(
            model_name='feedlyapisettings',
            name='FEEDLY_API_REFRESH_TOKEN',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
