# Generated by Django 2.2 on 2019-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190505_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='../static/images/favicon.png', upload_to='user_images/'),
        ),
    ]
