# Generated by Django 2.2 on 2019-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190526_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlyapisettings',
            name='api_requests_max',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text="If post doesn't have image on the server, URL link will be used."),
        ),
    ]
