# Generated by Django 2.2 on 2019-05-11 14:15

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190511_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAggregator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('url', models.URLField(max_length=85)),
                ('logo', imagekit.models.fields.ProcessedImageField(null=True, upload_to='news_site_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='news_site_logo',
        ),
        migrations.AddField(
            model_name='post',
            name='news_aggregator',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='posts.NewsAggregator'),
            preserve_default=False,
        ),
    ]
