# Generated by Django 2.2 on 2019-06-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_author'),
        ('posts', '0002_auto_20190526_1626'),
    ]

    operations = [
    ]
