# Generated by Django 2.2 on 2019-06-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190619_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feedly_engagement',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
