deploy:
  image: python:3-alpine
  before_script:
    - apk add --no-cache openssh-client bash rsync
    - pip install --no-cache-dir fabric
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$DEPLOY_KEY")'
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - fab -H $DEPLOY_ADDR deploy
  only:
    - master