image: docker:latest
services:
    - docker:dind

stages:
    - build
    - test
    - deploy

before_script:
    - apk add --no-cache python3-venv python3-pip
    - pip3 install docker-compose==1.24.0
    # log in Gitlab Docker registry
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose push

test:
    stage: test
    script:
        - docker-compose pull test
        - docker-compose run test

deploy:
    stage: deploy
    only:
        - master
    before_script:
        - apk add --no-cache openssh-client python3-venv python3-pip gcc g++ make libffi-dev openssl-dev bash rsync
        - pip3 install fabric==2.4.0 pycrypto
        - eval $(ssh-agent -s)
        - bash -c 'ssh-add <(echo "$DEPLOY_KEY")'
        - mkdir -p ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    script:
        - fab -H $DEPLOY_ADDR deploy