version: '3.7'

services:
    nginx:
        restart: always
        image: nginx:latest
        expose:
          - 8080
        ports:
          - "80:8080"
        volumes:
          - ./static:/srv/www/news-aggregator/static
          - ./media:/srv/www/news-aggregator/media
          - ./logs:/srv/www/news-aggregator/logs
          - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
          - python
    web:
        restart: always
        build:
            context: .
            dockerfile: docker/python/Dockerfile
        volumes:
            - .:/srv/www/news-aggregator
        expose:
          - 8000
        ports:
            - 8000:8000
        command: "gunicorn -c gunicorn.py adventure_agg.wsgi"
        depends_on:
          - celery
          - postgres
    rabbitmq:
      hostname: rabbit
      restart: always
      image: rabbitmq:latest
      ports:
        - "5673:5672"
    postgres:
        image: postgres:11.2-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: news_aggregator_user
            POSTGRES_PASSWORD: "&?6<&MUXr3#r^,"
            POSTGRES_DB: news_aggregator
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
        driver: local